apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongodb-latest
  namespace: cipher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-latest
  template:
    metadata:
      labels:
        app: mongodb-latest
    spec:
      containers:
      - name: mongo
        image: mongo:7.0
        command:
        - mongod
        - --bind_ip=0.0.0.0
        - --auth 
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
        name: mongo-volume
        readOnly: false
      volumes:
      - name: mongo-volume
      hostPath:
        path: /nfs/mongo
        type: Directory 
