apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb-latest
        image: mongo:7.0
        command:
        - mongod
        - --bind_ip=0.0.0.0
        - --auth 
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
        name: mongo-volume
        readOnly: false
      volumes:
      - name: mongo-volume
      hostPath:
        path: /nfs/mongo
        type: Directory 
